### ISSUE TITLE
[App]: Singularity

### ISSUE THREAD

**Issue by miaoabcd** [BounceBit-Labs/BounceBit-App-Store#18]
### App Name

Singularity

### Whitelist Address: BounceClub

0x639ebD317364962Ce8F785D3d523118841C2b81F

### Whitelist Address: Deployment

0x639ebD317364962Ce8F785D3d523118841C2b81F

### App Logo

![icon-128 1](https://github.com/BounceBit-Labs/BounceBit-App-Store/assets/6636096/c13c1e86-2ae4-4f02-aa59-c366bad3df1d)

### App Description

Singularity is ZK base, KYB/KYC permissioned DeFi access layer that provides access to popular protocols for onchain participants to transact with commercial confidentiality

### One Liner for Your App

Institutional-Grade DeFi Access Layer to Transact On-chain Confidentially

### App Category

Infrastructure

### App Banner

<img width="1356" alt="Screenshot 2024-06-06 at 11 53 34" src="https://github.com/BounceBit-Labs/BounceBit-App-Store/assets/6636096/10e879fe-0f71-49e2-b7bd-6e3112e0a897">

### App Link

app.thesingularity.network

### App Repo

https://github.com/portalgateme

**Comment by BounceBit** [comment]
Contract deployment and BoucneClub addresses have been whitelisted. Please check!
Gas tx: https://bbscan.io/tx/0xc6c871ca0169fde4dc50c30af9abf3b450931569403d8cbe8bffe131b7d48d1f
