### ISSUE TITLE
[App]: OmniBTC

### ISSUE THREAD

**Issue by Gary20001016** [BounceBit-Labs/BounceBit-App-Store#20]
### App Name

OmniBTC

### Whitelist Address: BounceClub

0x1f46baaa7e56e37d4236f48be193ac945459d9c8

### Whitelist Address: Deployment

0x68DB836dB23C11826010059Ba9174166A8AA0768

### App Logo

![omniBTC avatar](https://github.com/BounceBit-Labs/BounceBit-App-Store/assets/66670869/c99d9be2-35a5-4d3a-a385-9c64e1b0d522)

### App Description

OmniBTC is the first omnichain financial platform based on Wormhole, which has two products, namely OmniSwap and OmniLending and allows users to cross-chain swap/borrow/earn with one-click! OmniSwap is a cross-chain aggregator that currently supports 30 mainstream blockchains. Currently, the total transaction volume is 247,855,099 in US Dollar. Omnilending has over 10M US Dollars TVL in 6 chains.

### One Liner for Your App

OmniBTC provides bridge and lending for all chains' users.

### App Category

Others

### App Banner

<img width="1060" alt="bbpr" src="https://github.com/BounceBit-Labs/BounceBit-App-Store/assets/66670869/00fd48ef-7bad-4998-a0ec-74209ae727dc">

### App Link

https://app.omnibtc.finance/swap

### App Repo

https://github.com/OmniBTC

**Comment by BounceBit** [comment]
Contract deployment and BoucneClub  addresses have been whitelisted. Please check!
Gas tx: https://bbscan.io/tx/0xaf2fdb965c21abe6a54b3e7008f8c54fc3c34b72433ce7bf4668edb4491c2e58

**Comment by Gary20001016** [comment]
> Contract deployment and BoucneClub addresses have been whitelisted. Please check! Gas tx: https://bbscan.io/tx/0xaf2fdb965c21abe6a54b3e7008f8c54fc3c34b72433ce7bf4668edb4491c2e58

Thanks, we will deploy soon.
